### ISSUE TITLE
Автозапуск не отрабатывает, пункты для смены порта не работают

### ISSUE THREAD

**Issue by als-creator** [fatyzzz/Byedpi-Setup#4]
Может быть я чего-то не понимаю, само тестирование нормально проходит, при выборе установки службы порт всегда 8080, если запускаю повторно, то в итоге все равно 8080, если выбираю пункт смены порта, то в итоге все равно остается 8080, после работы скрипта пишет что добавлено в автозагрузку, но после ребута при выбраной конфигурации в браузере, что пишет нет интернета, ищу название службы, стартую, проверяю статус, заработало, выбираю sudo systemctl eneble ciadpi.service, работает на порту 8080 после ребута

● ciadpi.service - ByeDPI Proxy Service
     Loaded: loaded (/etc/systemd/system/ciadpi.service; enabled; preset: disabled)
     Active: active (running) since Tue 2024-12-17 18:23:09 +06; 38s ago
 Invocation: 67b6e29596804850bd12b22d6fef2a1e
   Main PID: 1131 (ciadpi-core)
      Tasks: 1 (limit: 23696)
     Memory: 292K (peak: 1.7M)
        CPU: 3ms
     CGroup: /system.slice/ciadpi.service
             └─1131 /opt/ciadpi/ciadpi-core --ip 127.0.0.1 --port 8080 -Kt,h -s0 -o1 -Ar -o1 -At -f-1 --md5sig -r1+s -As,n -Ku -a5 -s443+s -d80+s -d443+s -s80+s -An

выбираю пункт смена порта службы, пишет порт изменен, делаю рестарт, статус не меняется, делаю ребут пк, статус не меняется, на 8080 ютуб с данными настройками работает, но хотелось бы разобраться в чем проблем
и хорошо бы в описании скрипта указать что служба называется ciadpi.service, а то я пытался запустить byedpi.service, не мог понять почему не работает

**Comment by fatyzzz** [comment]
у вас осталась легаси служба старого билда
пропишите команды по очереди:
sudo systemctl stop ciadpi
sudo rm /etc/systemd/ciadpi.service
проверить, не осталось ли судо службы
sudo systemctl status ciadpi
если нет, запустить скрипт. Если проблема останется повторно, проверьте systemctl --user status ciadpi и отпишите по результату
название службы в вывод добавлю, да.

**Comment by als-creator** [comment]
sudo rm /etc/systemd/ciadpi.service не работает
у меня в выводе выше Loaded: loaded (/etc/systemd/system/ciadpi.service; enabled; preset: disabled)
удалил
![image](https://github.com/user-attachments/assets/e2f810b1-383b-4983-b318-b8f5597057e9)

[WARN] 2024-12-18 00:17:14: Топ 10 конфигураций:
0) -Kt,h -n ya.ru -f7 --md5sig -d1 -s0+s -s3+s -s6+s -s9+s -s12+s -s15+s -s20+s -o10000+s -s30+s -An -Ku -a5 -An (Успех: 3%, 1/33, Неуспешно: 32####)
1) -Kt,h -d7 -s2 -An -Ku -a9 -An (Успех: 0%, 0/33, Неуспешно: 33####)
2) -Kt,h -q1 -r25+s -An -Ku -a7 -An (Успех: 0%, 0/33, Неуспешно: 33####)
3) -Kt,h -s1 -f-1 --md5sig -b661 -An -Ku -a5 -An (Успех: 0%, 0/33, Неуспешно: 33####)
4) -Kt,h -s1 -d3+s -Mh,d -At -r1+s -r3+s -An -Ku -a1 -An (Успех: 0%, 0/33, Неуспешно: 33####)
5) -Kt,h -q1+s -s29+s -o5+s -f-1 --md5sig -Asn -Ku -a5 -An (Успех: 0%, 0/33, Неуспешно: 33####)
6) -Kt,h -s1 -q1 -Art -f-1 --md5sig -r1+s -As,n -Ku -a1 -An (Успех: 0%, 0/33, Неуспешно: 33####)
7) -Kt,h -s1 -q1 -Art -f-1 --md5sig -r1+s -As,n -Ku -a1 -An (Успех: 0%, 0/33, Неуспешно: 33####)
8) -Kt,h -d1 -s1+s -s4 -d5+s -d8 -s10+s -d20+s -An -Ku -a1 -An (Успех: 0%, 0/33, Неуспешно: 33####)
9) -Kt,h -s0 -o1 -Ar -o1 -At -f-1 --md5sig -r1+s -As,n -Ku -a5 -An (Успех: 0%, 0/33, Неуспешно: 33####)
Выберите номер конфигурации: 0
[WARN] 2024-12-18 00:17:39: Директория /home/als/.config/systemd/user уже существует.
[INFO] 2024-12-18 00:17:40: Служба добавлена в автозапуск
[INFO] 2024-12-18 00:17:40: Установка ByeDPI завершена. Служба ciadpi запущена от пользователя с настройкой: -Kt,h -n ya.ru -f7 --md5sig -d1 -s0+s -s3+s -s6+s -s9+s -s12+s -s15+s -s20+s -o10000+s -s30+s -An -Ku -a5 -An 
[WARN] 2024-12-18 00:17:40: Информация для подключения Socks5 прокси
[WARN] 2024-12-18 00:17:40: Айпи: 127.0.0.1
[WARN] 2024-12-18 00:17:40: Порт: 13228
[als@als-ms7c52 ~]$ sudo systemctl status ciadpi.service
[sudo] пароль для als: 
Unit ciadpi.service could not be found.
[als@als-ms7c52 ~]$ sudo systemctl enable ciadpi.service
мне юнит обратно вернуть?

**Comment by als-creator** [comment]
повторно скрипт запустил, пишет все настроено
в каталоге **ls /etc/systemd**

coredump.conf  journald.conf    journal-remote.conf  logind.conf    logind.conf.pacnew  network.conf.d  oomd.conf    resolved.conf  system       timesyncd.conf  user.conf
homed.conf     journald.conf.d  journal-upload.conf  logind.conf.d  network             networkd.conf   pstore.conf  sleep.conf     system.conf  user            zram-generator.conf

**ls /etc/systemd/system**
bluetooth.target.wants              dbus-org.freedesktop.nm-dispatcher.service  display-manager.service  network-online.target.wants  sysinit.target.wants
dbus-org.bluez.service              dbus-org.freedesktop.timesync1.service      getty.target.wants       printer.target.wants         timers.target.wants
dbus-org.freedesktop.Avahi.service  default.target                              multi-user.target.wants  sockets.target.wants

**sudo systemctl status ciadpi.service**

Unit ciadpi.service could not be found.

с настройками на порт 13228 все работает, предполагаю после ребута отвалится

**sudo systemctl stop ciadpi.service**

Failed to stop ciadpi.service: Unit ciadpi.service not loaded. 

не понимаю как это работает и где юнит

**Comment by als-creator** [comment]
погрепал
![image](https://github.com/user-attachments/assets/f258de31-eb3c-45d9-b7a6-a81a7f015e29)

**Comment by fatyzzz** [comment]
все заработало, верно?

**Comment by fatyzzz** [comment]
если что прро смену службы на пользовательскую еще в первом сообщении написал, но ладно, бывает)

**Comment by fatyzzz** [comment]
если снес службу в etc/systemd,  то успешно стартанет пользовательская
systemctl --user status ciadpi

**Comment by als-creator** [comment]
да я уже вернул все обратно, хорошо бы все это в ман для пользователей скрипта оформить
а с чем могут быть связаны такие низкие показатели работы у меня? сейчас попробую через другой роутер потестить

**Comment by fatyzzz** [comment]
> да я уже вернул все обратно, хорошо бы все это в ман для пользователей скрипта оформить а с чем могут быть связаны такие низкие показатели работы у меня? сейчас попробую через другой роутер потестить

вероятно ваш провайдер блокирует айпи адреса. или стоит очень жесткое тспу. еще замечал плохие результаты с виртуалок

**Comment by fatyzzz** [comment]
запустите тест и скиньте сюда результаты пожалуйста

**Comment by als-creator** [comment]
[WARN] 2024-12-18 12:57:26: Топ 10 конфигураций:
0) -Kt,h -s0 -o1 -d1 -r1+s -Ar -o1 -At -f-1 --md5sig -r1+s -As,n -Ku -a5 -An (Успех: 54%, 18/33, Неуспешно: 15####)
1) -Kt,h -s1 -f-1 --md5sig -b661 -An -Ku -a5 -An (Успех: 48%, 16/33, Неуспешно: 17####)
2) -Kt,h -s0 -o1 -Ar -o1 -At -f-1 --md5sig -r1+s -As -b+500 --tls-sni=www.google.com -An -Ku -a5 -An (Успех: 45%, 15/33, Неуспешно: 18####)
3) -Kt,h -s1 -q1 -Art -f-1 --md5sig -r1+s -As,n -Ku -a1 -An (Успех: 42%, 14/33, Неуспешно: 19####)
4) -Kt,h -o3+sn -q4+h -b8999 -f-1 --md5sig -As -s443+s -d80+s -An -Ku -a5 -An (Успех: 42%, 14/33, Неуспешно: 19####)
5) -Kt,h -s9+n -d7+h -q9+s -b3023 -f-1 --md5sig -n vk.com -As -s443+s -d80+s -An -Ku -a5 -An (Успех: 42%, 14/33, Неуспешно: 19####)
6) -Kt,h -q1 -r25+s -An -Ku -a7 -An (Успех: 39%, 13/33, Неуспешно: 20####)
7) -Kt,h -s0 -o1 -Ar -o1 -At -f-1 --md5sig -r1+s -As,n -Ku -a5 -An (Успех: 39%, 13/33, Неуспешно: 20####)
8) -Kt,h -s6+n -d9+n -d18+n -q6+hn -f-1 --md5sig -As -s443+s -d80+s -An -Ku -a5 -An (Успех: 39%, 13/33, Неуспешно: 20####)
9) -Kt,h -s1 -q1 -Ar -s5 -o1+s -At -f-1 --md5sig -r1+s -As -s1 -o1+s -s-1 -An -Ku -a1 -An (Успех: 39%, 13/33, Неуспешно: 20####)

верхняя
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://rr1---sn-ug5onuxaxjvh-p3ul.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://rr10---sn-gvnuxaxjvh-304z.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://rr1---sn-4axm-n8vs.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://i.ytimg.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://rr1---sn-ug5onuxaxjvh-n8v6.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://jnn-pa.googleapis.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://signaler-pa.youtube.com: 404)
[INFO] 2024-12-18 12:55:58:   ✓ OK (https://rr1---sn-gvnuxaxjvh-o8ge.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://rr4---sn-q4flrnsl.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://youtubei.googleapis.com: 405)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://manifest.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://yt4.ggpht.com: 400)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rr2---sn-q4fl6ndl.googlevideo.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rr12---sn-gvnuxaxjvh-bvwz.googlevideo.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rr1---sn-gvnuxaxjvh-5gie.googlevideo.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rr1---sn-8ph2xajvh-5xge.googlevideo.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rr1---sn-q4fl6n6y.googlevideo.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://googleapis.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://meduza.io: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://hongkong11078.discord.media: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rr1---sn-hxb54vo-v8ck.googlevideo.com: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://finland10100.discord.media: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://russia3872.discord.media: 000)
[ERROR] 2024-12-18 12:55:59:   ✗ FAILED (https://rotterdam8003.discord.media: 000)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://rr1---sn-u5uuxaxjvhg0-ocje.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://rr4---sn-jvhnu5g-c35d.googlevideo.com: 404)
[INFO] 2024-12-18 12:55:59:   ✓ OK (https://gstatic.com: 301)
[INFO] 2024-12-18 12:56:00:   ✓ OK (https://yt3.ggpht.com: 400)
[INFO] 2024-12-18 12:56:00:   ✓ OK (https://play.google.com: 302)
[INFO] 2024-12-18 12:56:00:   ✓ OK (https://rr2---sn-hgn7ynek.googlevideo.com: 404)
[ERROR] 2024-12-18 12:56:00:   ✗ FAILED (https://www.youtube.com: 000)
[ERROR] 2024-12-18 12:56:00:   ✗ FAILED (https://rr5---sn-gvnuxaxjvh-n8vk.googlevideo.com: 000)
[ERROR] 2024-12-18 12:56:00:   ✗ FAILED (https://discord.com: 000)

другие пробовать не буду, так как особого смысла нет, провайдер наверно блочит, мобильные говорят всегда самые активные, на своем старом микро роутере на свежей прошивке падавана нашел вот такое, теперь наверно это пока это будет мой любимый роутер со вторым вариантом обхода плюсом к byedpi

![image](https://github.com/user-attachments/assets/7a2274e2-621a-4d36-9b64-cf93ddeaca29)
![image](https://github.com/user-attachments/assets/ed4fdaa6-1e7b-4f2e-baa2-bdb545a8ea03)

**Comment by fatyzzz** [comment]
на роутере запрет, его если установить получше байдпи будет, если роутер вывезет

**Comment by fatyzzz** [comment]
проблема исправлена, улучшение добавлено

**Comment by als-creator** [comment]
а где скрипт для пользователя прописывает значения переменных для порта и правил? я смотрю раньше они указывались явно, а сейчас переменные вроде в конфиге пользователя, где их править руками? по умолчанию используется не пользовательский конфиг если он есть? 

$ cat /home/als/.config/systemd/user/multi-user.target.wants/ciadpi.service
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/als/.config/systemd/user/multi-user.target.wants/ciadpi.service
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [Unit]
   2   │ Description=ByeDPI Proxy Service
   3   │ Documentation=https://github.com/fatyzzz/Byedpi-Setup
   4   │ Wants=network-online.target
   5   │ After=network-online.target nss-lookup.target
   6   │ 
   7   │ [Service]
   8   │ EnvironmentFile=-%h/.config/byedpi.conf
   9   │ ExecStart=%h/ciadpi/ciadpi-core --ip 127.0.0.1 --port $SEL_PORT $SEL_SETTINGS
  10   │ Restart=on-failure
  11   │ RestartSec=5s
  12   │ 
  13   │ [Install]
  14   │ WantedBy=default.target
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┬─[als@als-ms7c52:~]─[13:40:55]
╰─>$ cat /home/als/.config/systemd/user/default.target.wants/ciadpi.service
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/als/.config/systemd/user/default.target.wants/ciadpi.service
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [Unit]
   2   │ Description=ByeDPI Proxy Service
   3   │ Documentation=https://github.com/fatyzzz/Byedpi-Setup
   4   │ Wants=network-online.target
   5   │ After=network-online.target nss-lookup.target
   6   │ 
   7   │ [Service]
   8   │ EnvironmentFile=-%h/.config/byedpi.conf
   9   │ ExecStart=%h/ciadpi/ciadpi-core --ip 127.0.0.1 --port $SEL_PORT $SEL_SETTINGS
  10   │ Restart=on-failure
  11   │ RestartSec=5s
  12   │ 
  13   │ [Install]
  14   │ WantedBy=default.target
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┬─[als@als-ms7c52:~]─[13:41:26]
╰─>$ cat /home/als/.config-att/config-att-2024-12-21-19-35-19/systemd/user/ciadpi.service

───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/als/.config-att/config-att-2024-12-21-19-35-19/systemd/user/ciadpi.service
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [Unit]
   2   │ Description=ByeDPI Proxy Service
   3   │ After=network.target
   4   │ 
   5   │ [Service]
   6   │ WorkingDirectory=/home/als/ciadpi/
   7   │ ExecStart=/home/als/ciadpi/ciadpi-core --ip 127.0.0.1 --port 14288 -Kt,h -q1+s -s14+s -s29+s -s30+s -o5+s -f-1 --md5sig -Asn -Ku -a5 -An
   8   │ Restart=on-failure
   9   │ RestartSec=5s
  10   │ 
  11   │ [Install]
  12   │ WantedBy=multi-user.target

**Comment by als-creator** [comment]
в скрипте что то менялось? служба юзера работает, порт свободен, порт пробовал менять, расширение прокси пробовал менять, ничего е работает, пишет проблема с прокси сервером
